# Generated by Django 4.1.3 on 2022-11-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_artist_playlist_song_artist_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='albums', to='jams.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='artists', to='jams.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlists', to='jams.playlist'),
        ),
    ]
