# Generated by Django 4.1.3 on 2022-11-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_alter_song_album_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='album_songs', to='jams.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='artists_songs', to='jams.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlists_songs', to='jams.playlist'),
        ),
    ]
