# Generated by Django 4.1.3 on 2022-11-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_alter_song_album_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_title',
            new_name='title',
        ),
    ]
